name: Deploy to staging

on:
  push:
    branches:
      - develop
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Generate wrangler.toml
        run: npm run generate-dev-config

      - name: Publish app
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: |
            npm install
          command: deploy --env staging
          environment: staging
          secrets: |
            CF_ACCOUNT_ID
            STAGING_SCRIPT_NAME
            STAGING_KV_ID
            STAGING_BUCKET_NAME
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          STAGING_SCRIPT_NAME: ${{ secrets.STAGING_SCRIPT_NAME }}
          STAGING_KV_ID: ${{ secrets.STAGING_KV_ID }}
          STAGING_BUCKET_NAME: ${{ secrets.STAGING_BUCKET_NAME }}
